language: perl
env:
    - LATEXMK_BACKEND=xelatex
    - LATEXMK_BACKEND=lualatex
before_install:
    - tools/travis-tl.sh
    - export PATH=~/tl/bin/x86_64-linux:$PATH
install:
    - tlmgr install $(<tools/packages) || true
script:
    - cd tests
    - make
    - make check
# cache:
#     directories:
#         - ~/tl
