language: perl
before_install:
    - tools/travis-tl.sh
    - export PATH=~/tl/bin/x86_64-linux:$PATH
install:
    - tlmgr install $(<tools/packages) || true
script:
    - lualatex test.tex
# cache:
#     directories:
#         - ~/tl
