language: perl
sudo: false
env:
    - LATEXMK_BACKEND=xelatex
    - LATEXMK_BACKEND=lualatex

cache:
    directories:
        - ~/tl

before_install:
    - tools/travis-tl.sh
    - export PATH=~/tl/bin/x86_64-linux:$PATH

install:
    - tlmgr install $(<tools/packages) || true

script:
    - tools/setup-hooks.sh
    - git checkout
    - cd tests
    - make
    - make check
    - make lacheck
